#!/bin/bash

# Author: Noé Paniagua

#Colours
greenColour="\e[0;32m\033[1m"
endColour="\033[0m\e[0m"
redColour="\e[0;31m\033[1m"
blueColour="\e[0;34m\033[1m"
yellowColour="\e[0;33m\033[1m"
purpleColour="\e[0;35m\033[1m"
turquoiseColour="\e[0;36m\033[1m"
grayColour="\e[0;37m\033[1m"

#Configuration variables
yamlFile="usbInfo.yaml"

saveNewDevice() {
    fd=$1

    #Read the data from usb and clean the strings
    vendorID=$(udevadm info --name=${fd/$"/dev/"/} 2>/dev/null | grep -i ID_VENDOR= | awk -F= '{print $2}')
    serialNumber=$(udevadm info --name=${fd/$"/dev/"/} 2>/dev/null | grep -i ID_SERIAL_SHORT= | awk -F= '{print $2}')

    #Search the serial id in the database
    nameFound=$(searchIntoYaml "ID_SERIAL_SHORT" $serialNumber)
    if [ ! -n $nameFound ]; then
		echo -e "${purpleColour}whusb${endColour}: ${turquoiseColour}$fd${endColour} exists in database, named as ${yellowColour}$nameFound${endColour}"
		return
    else
    	echo -e -n "${purpleColour}whusb${endColour}: Hi, say a name for ${turquoiseColour}$fd${endColour}: "
		read newName
		yq eval -i ".$newName.ID_VENDOR = \"$vendorID\"" "$yamlFile"
		yq eval -i ".$newName.ID_SERIAL_SHORT = \"$serialNumber\"" "$yamlFile"
    fi
}

showDevices() {
    numDevices=$(yq eval "keys | length" "$yamlFile")

    #Must search each saved device
    for i in $(seq 1 $numDevices); do
        pathG="/dev"

        #Must search the value (whileeeeeee)
        for singleFD in "$pathG"/*; do
            serialNumber=$(udevadm info --name="$singleFD" 2>/dev/null | grep -i ID_SERIAL_SHORT= | awk -F= '{print $2}')
            if [ -n "$serialNumber" ]; then
                nameFound=$(searchIntoYaml "ID_SERIAL_SHORT" $serialNumber)
                if [ -n "$nameFound" ]; then
                    echo -e "${purpleColour}whusb${endColour}: ${turquoiseColour}$singleFD${endColour} is in truth your bb ${yellowColour}$nameFound${endColour}"
                    break
                fi
            fi
        done
    done

    echo -e "${purpleColour}whusb${endColour}: There aren't more known devices :("
}

searchIntoYaml() {
	yamlElement=$1
    parameter=$2

    if [ ! -s "$usbYaml" ]; then
    	for names in $(yq eval "keys" "$yamlFile" | awk '{print $2}'); do
        	if [[ $parameter = $(yq eval ".$names.$yamlElement" "$yamlFile") ]]; then
            	echo $names
            	return
        	fi
    	done
    fi
}

showHelp() {
	echo -e "La estas liando negro esto va asi..."
}


# MAIN FUNCTION

# Need to create the file??
if [ ! -f "$yamlFile" ]; then
    #echo "{}" > "$yamlFile"
    touch "$yamlFile"
    echo -e "${purpleColour}whusb${endColour}:A yaml file will store usb data in $(pwd)/$yamlFile..."

fi

# Read parameters and execute functions
parameter_counter=0; while getopts "n:sh" arg; do
	case $arg in 
		n) saveNewDevice $OPTARG; exit 0;;
		s) showDevices; exit 0;;
		h) showHelp; exit 0;;
	esac
done
